// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentRouter.Infrastructure.Data;

#nullable disable

namespace PaymentRouter.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentRouterDbContext))]
    [Migration("20260807130415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentRouter.Domain.Models.PaymentProvider", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CircuitBreakerState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CostConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SupportedCurrencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("SupportedMethods")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProviderId");

                    b.HasIndex("HealthStatus")
                        .HasDatabaseName("idx_payment_providers_health_status");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("idx_payment_providers_is_enabled");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_payment_providers_priority");

                    b.ToTable("payment_providers", "payment_router");
                });

            modelBuilder.Entity("PaymentRouter.Domain.Models.RoutingDecision", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("AlternativeProviderIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CostEstimateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("DecisionMadeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DecisionId");

                    b.HasIndex("DecisionMadeAt")
                        .HasDatabaseName("idx_routing_decisions_decision_made_at");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_routing_decisions_merchant_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_routing_decisions_payment_id");

                    b.HasIndex("SelectedProviderId")
                        .HasDatabaseName("idx_routing_decisions_selected_provider");

                    b.ToTable("routing_decisions", "payment_router");
                });

            modelBuilder.Entity("PaymentRouter.Domain.Models.RoutingRule", b =>
                {
                    b.Property<string>("RuleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("PreferredProviderIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RuleId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_routing_rules_is_active");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_routing_rules_merchant_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_routing_rules_priority");

                    b.HasIndex("MerchantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_routing_rules_merchant_name");

                    b.ToTable("routing_rules", "payment_router");
                });
#pragma warning restore 612, 618
        }
    }
}
