version: '3.9'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    command: [ "tempo", "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - "4318:4318"
      - "8889:8889"