global:
  repoURL: "https://github.com/DuyDang112/payment-system.git"
  targetRevision: "develop"
  destinationServer: "https://kubernetes.default.svc"
  project: "monitoring"

applications:
  loki:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/loki
    valuesFile: deployments/argo-monitoring-apps/values/loki.yaml

  kube-prometheus-stack:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/kube-prometheus-stack
    valuesFile: deployments/argo-monitoring-apps/values/kube-prometheus-stack.yaml

  tempo:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/tempo
    valuesFile: deployments/argo-monitoring-apps/values/tempo.yaml

  otel-collector:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/otel-collector
    valuesFile: deployments/argo-monitoring-apps/values/otel-collector.yaml



