apiVersion: v1
kind: Secret
metadata:
  name: apigateway-secret
  namespace: payment-system-dev
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: paymentprocessing-secret
  namespace: payment-system-dev
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: paymentrouter-secret
  namespace: payment-system-dev
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: riskassessment-secret
  namespace: payment-system-dev
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: bankadapter-secret
  namespace: payment-system-dev
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgresql.database.svc.cluster.local;Port=5432;Database=bank_adapter_dev;Username=paymentuser;Password=Payment123!"