apiVersion: v1
kind: Secret
metadata:
  name: apigateway-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: paymentprocessing-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: paymentrouter-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: riskassessment-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: bankadapter-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"
---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-secret
  namespace: payment-system-prod
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "__value__"