// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiskAssessment.Infrastructure.Data;

#nullable disable

namespace RiskAssessment.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RiskAssessmentDbContext))]
    partial class RiskAssessmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("risk_assessment")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiskAssessment.Domain.Models.BlacklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("added_by");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_value");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_blacklist_entries");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_blacklist_entity_type");

                    b.HasIndex("EntityValue")
                        .HasDatabaseName("idx_blacklist_entity_value");

                    b.HasIndex("EntityType", "EntityValue")
                        .IsUnique()
                        .HasDatabaseName("uq_blacklist_entry");

                    b.ToTable("blacklist_entries", "risk_assessment");
                });

            modelBuilder.Entity("RiskAssessment.Domain.Models.MerchantRiskProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AutoRejectThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(80)
                        .HasColumnName("auto_reject_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ManualReviewThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("manual_review_threshold");

                    b.Property<decimal?>("MaxTransactionAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_transaction_amount");

                    b.Property<string>("MaxTransactionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("max_transaction_currency");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("merchant_id");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_merchant_risk_profiles");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasDatabaseName("uq_merchant_id");

                    b.ToTable("merchant_risk_profiles", "risk_assessment");
                });

            modelBuilder.Entity("RiskAssessment.Domain.Models.RiskEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvaluationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("merchant_id");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_id");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_version");

                    b.HasKey("Id")
                        .HasName("pk_risk_evaluations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_customer_id");

                    b.HasIndex("Decision")
                        .HasDatabaseName("idx_risk_decision");

                    b.HasIndex("EvaluatedAt")
                        .HasDatabaseName("idx_evaluated_at");

                    b.HasIndex("EvaluationId")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_evaluations_evaluation_id");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("idx_merchant_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_payment_id");

                    b.ToTable("risk_evaluations", "risk_assessment");
                });

            modelBuilder.Entity("RiskAssessment.Domain.Models.RiskRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("JSONB")
                        .HasColumnName("conditions_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rule_name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.Property<int>("ScoreImpact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score_impact");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_risk_rules");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_priority");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("idx_rule_id");

                    b.HasIndex("RuleType")
                        .HasDatabaseName("idx_rule_type");

                    b.HasIndex("RuleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_rule_version");

                    b.ToTable("risk_rules", "risk_assessment");
                });

            modelBuilder.Entity("RiskAssessment.Domain.Models.WhitelistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("added_by");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EntityValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_value");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_whitelist_entries");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("idx_whitelist_entity_type");

                    b.HasIndex("EntityValue")
                        .HasDatabaseName("idx_whitelist_entity_value");

                    b.HasIndex("EntityType", "EntityValue")
                        .IsUnique()
                        .HasDatabaseName("uq_whitelist_entry");

                    b.ToTable("whitelist_entries", "risk_assessment");
                });
#pragma warning restore 612, 618
        }
    }
}
