// <auto-generated />
using System;
using BankAdapter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankAdapter.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BankAdapterDbContext))]
    partial class BankAdapterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bank_adapter")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankAdapter.Domain.Provider", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("integration_id");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("api_version");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_id");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer")
                        .HasColumnName("provider_type");

                    b.Property<string>("RateLimits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rate_limits");

                    b.Property<string>("RetryConfig")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retry_config");

                    b.Property<string>("SupportedOperations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supported_operations");

                    b.Property<string>("Timeouts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeouts");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IntegrationId");

                    b.HasIndex("ProviderId");

                    b.ToTable("providers", "bank_adapter");
                });

            modelBuilder.Entity("BankAdapter.Domain.ProviderRequestLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_id");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_payload");

                    b.Property<DateTime>("RequestSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_sent_at");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_payload");

                    b.Property<DateTime?>("ResponseReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_received_at");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("LogId");

                    b.HasIndex("Operation");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequestSentAt");

                    b.HasIndex("Result");

                    b.ToTable("provider_request_logs", "bank_adapter");
                });
#pragma warning restore 612, 618
        }
    }
}
